name: Hello World

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24.18.0
      - run: npm ci
      - run: npm run build
      - run: | 
           if [ ! -d "dist" ]; then
             echo "Le dossier dist n'existe pas. La construction a échoué."
             exit 1
           fi
      - uses: actions/upload-artifact@v7
        with:
          name: build
          path: dist/
      - run: |
          echo "## BUILD" >> "$GITHUB_STEP_SUMMARY"
